name: lifx_http_api
description: A dart implementation of the LIFX HTTP API for smart LED bulbs.
version: 0.0.2
homepage: https://github.com/nathanielgreen/lifx_http_api
repository: https://github.com/nathanielgreen/lifx_http_api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dotenv: ^3.0.0
  http: ^0.13.3
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
