name: lifx_cli
description: A REPL to interact with the LIFX HTTP API
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dart_console: ^1.1.2
  lifx_http_api:
    path: ../../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
